In [40]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv

In [41]:
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split,cross_val_score

In [42]:
df=pd.read_csv('/kaggle/input/datasets/yasserh/titanic-dataset/Titanic-Dataset.csv',usecols=['Age','SibSp','Parch','Pclass','Survived'])

In [43]:
df.head()

   Survived  Pclass   Age  SibSp  Parch
0         0       3  22.0      1      0
1         1       1  38.0      1      0
2         1       3  26.0      0      0
3         1       1  35.0      1      0
4         0       3  35.0      0      0

In [45]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
SibSp         0
Parch         0
dtype: int64

In [49]:
df.dropna(inplace=True)

In [51]:
df.isnull().sum()

Survived    0
Pclass      0
Age         0
SibSp       0
Parch       0
dtype: int64

In [52]:
x=df.iloc[:,1:5]
y=df.iloc[: ,0:1]

In [55]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [56]:
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=10))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

np.float64(0.6921165884194054)

# Feature Construction

In [57]:
df['family_size']=df['SibSp']+df['Parch']+1

In [58]:
df.head()

   Survived  Pclass   Age  SibSp  Parch  family_size
0         0       3  22.0      1      0            2
1         1       1  38.0      1      0            2
2         1       3  26.0      0      0            1
3         1       1  35.0      1      0            2
4         0       3  35.0      0      0            1

In [59]:
x=df[['Pclass','Age','family_size']]
y=df['Survived']

In [60]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
np.mean(cross_val_score(LogisticRegression(),x,y,scoring='accuracy',cv=10))

np.float64(0.6977308294209702)

In [62]:
def myfun(num):
    if num==1:
        return 0
    elif num>1 and num<=4:
        return 1
    else:
        return 2

In [63]:
df['family_type']=df['family_size'].apply(myfun)

In [64]:
df.head()

   Survived  Pclass   Age  SibSp  Parch  family_size  family_type
0         0       3  22.0      1      0            2            1
1         1       1  38.0      1      0            2            1
2         1       3  26.0      0      0            1            0
3         1       1  35.0      1      0            2            1
4         0       3  35.0      0      0            1            0

In [65]:
df.drop(columns=['SibSp','Parch','family_size'])

     Survived  Pclass   Age  family_type
0           0       3  22.0            1
1           1       1  38.0            1
2           1       3  26.0            0
3           1       1  35.0            1
4           0       3  35.0            0
..        ...     ...   ...          ...
885         0       3  39.0            2
886         0       2  27.0            0
887         1       1  19.0            0
889         1       1  26.0            0
890         0       3  32.0            0

[714 rows x 4 columns]

In [75]:
a=df[['Pclass','Age','family_type']]
b=df['Survived']

In [84]:
x_train,x_test,y_train,y_test=train_test_split(a,b,test_size=0.2)
np.mean(cross_val_score(LogisticRegression(),a,b,scoring='accuracy',cv=20))

np.float64(0.7003174603174602)