In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/vitthalbulbule/cars-csv/cars.csv

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/kaggle/input/datasets/vitthalbulbule/cars-csv/cars.csv')

In [4]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

## One Hot Encoding  Using the pandas

In [12]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [14]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [15]:
pd.get_dummies(df[['fuel','owner']],drop_first=True,dtype=int)

,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,1,0,0,0,0,0,0
1,1,0,0,0,1,0,0
2,0,0,1,0,0,0,1
3,1,0,0,0,0,0,0
4,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...
8123,0,0,1,0,0,0,0
8124,1,0,0,1,0,0,0
8125,1,0,0,0,0,0,0
8126,1,0,0,0,0,0,0
8127,1,0,0,0,0,0,0

In [19]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

#### But Mainly Machine Learning Engineer Doing One Hot Encoding using the SCIKIT learn insted of Pandas

In [29]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[ : , :-1],test_size=0.2)

In [30]:
from sklearn.preprocessing import OneHotEncoder
oe=OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [32]:
x_train_new=oe.fit_transform(x_train[['fuel','owner']])
x_test_new=oe.transform(x_test[['fuel','owner']])

In [34]:
x_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [35]:
x_test_new

array([[0, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0]], dtype=int32)

In [45]:
final_train=np.hstack((x_train[['brand','km_driven']].values,x_train_new))
final_test=np.hstack((x_test[['brand','km_driven']].values,x_test_new))

In [42]:
final_train

array([['BMW', 7500, 1, ..., 0, 0, 0],
       ['Maruti', 110000, 0, ..., 1, 0, 0],
       ['BMW', 8500, 1, ..., 0, 0, 0],
       ...,
       ['Mahindra', 120000, 1, ..., 0, 0, 0],
       ['Maruti', 35000, 0, ..., 0, 0, 0],
       ['Hyundai', 20000, 0, ..., 0, 0, 0]], dtype=object)

In [46]:
final_test

array([['Hyundai', 20000, 0, ..., 1, 0, 0],
       ['Hyundai', 56000, 1, ..., 0, 0, 0],
       ['Volkswagen', 75000, 1, ..., 0, 0, 0],
       ...,
       ['Volkswagen', 7000, 0, ..., 0, 0, 0],
       ['Mahindra', 24000, 1, ..., 0, 0, 0],
       ['Maruti', 29500, 0, ..., 0, 0, 0]], dtype=object)

In [67]:
final_data=pd.DataFrame(final_train)
final_test_data=pd.DataFrame(final_test)

In [77]:
final_data

             0       1  2  3  4  5  6  7  8
0          BMW    7500  1  0  0  0  0  0  0
1       Maruti  110000  0  0  1  0  1  0  0
2          BMW    8500  1  0  0  0  0  0  0
3          BMW    7500  1  0  0  0  0  0  0
4       Maruti   24000  1  0  0  0  0  0  0
...        ...     ... .. .. .. .. .. .. ..
6497   Hyundai   50000  1  0  0  0  0  0  0
6498    Maruti   29000  0  0  1  0  0  0  0
6499  Mahindra  120000  1  0  0  0  0  0  0
6500    Maruti   35000  0  0  1  0  0  0  0
6501   Hyundai   20000  0  0  1  0  0  0  0

[6502 rows x 9 columns]

In [76]:
final_test_data

               0       1  2  3  4  5  6  7  8
0        Hyundai   20000  0  0  1  0  1  0  0
1        Hyundai   56000  1  0  0  0  0  0  0
2     Volkswagen   75000  1  0  0  0  0  0  0
3       Mahindra  110000  1  0  0  0  0  0  0
4            BMW    7500  1  0  0  0  0  0  0
...          ...     ... .. .. .. .. .. .. ..
1621     Hyundai   80000  0  0  1  0  0  0  0
1622       Honda   40000  0  0  1  0  0  0  0
1623  Volkswagen    7000  0  0  1  0  0  0  0
1624    Mahindra   24000  1  0  0  0  0  0  0
1625      Maruti   29500  0  0  1  0  0  0  0

[1626 rows x 9 columns]

## One Hot Encoding With Top Categories

In [ ]:
# keep top 3 frequent categories
top_categories = df['Car_Model'].value_counts().index[:3]

# replace remaining with 'Other'
df['Car_Model'] = df['Car_Model'].apply(
    lambda x: x if x in top_categories else 'Other'
)

# one hot encoding
ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(df[['Car_Model']])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out()
)

print(encoded_df)

In [70]:
counts=df['brand'].value_counts()

In [71]:
df['brand'].nunique()
threshold=100

In [72]:
repl=counts[counts<=threshold].index

In [75]:
pd.get_dummies(df['brand'].replace(repl,'Uncommon'),dtype=int,drop_first=True)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Uncommon,Volkswagen
0,0,0,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,1,0,0,0,0
2,0,0,1,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,0,0,0,1,0,0,0,0,0,0,0,0
8124,0,0,0,1,0,0,0,0,0,0,0,0
8125,0,0,0,0,0,1,0,0,0,0,0,0
8126,0,0,0,0,0,0,0,0,1,0,0,0
8127,0,0,0,0,0,0,0,0,1,0,0,0