In [57]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

In [58]:
import pandas as pd
import numpy as np

# Now I will Do the Separate pipeline for each feature and apply it using final Pipeline

In [59]:
import pandas as pd

In [60]:
df=pd.read_csv('/kaggle/input/competitions/titanic/train.csv')

In [61]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [62]:
df=df.drop(columns=['PassengerId','Name','Cabin',"Ticket"],axis = 1)

In [63]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [64]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [65]:
# Age_pipeline -> For fill the missing values
# Embarked & Sex -> for filling missing values and one hot encoding
# column Transformer
# Final Pipeline

In [66]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [67]:
x=df.iloc[:,1:8]
y=df.iloc[:,0:1]

In [68]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

## Age_pipeline

In [69]:

age_pipe=Pipeline([
    ('impute',SimpleImputer(strategy='mean'))
])

## cat_pipeline

In [70]:
cat_pipe=Pipeline([
    ('impute',SimpleImputer(strategy='most_frequent')),
    ('OneHotEncode',OneHotEncoder(drop='first'))
])

## Column Transformer

In [71]:
preprocessing = ColumnTransformer([
    ('age',age_pipe,[2]),
    ('category',cat_pipe,[1,6])
],remainder='passthrough')

# Final Pipeline

In [72]:
from sklearn.linear_model import LogisticRegression

pipe=Pipeline([
    ('preprocess',preprocessing),
    ('Scaling',StandardScaler()),
    ('model',LogisticRegression())
])

In [73]:
pipe.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Pipeline(steps=[('preprocess',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('age',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer())]),
                                                  [2]),
                                                 ('category',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('OneHotEncode',
                                                                   OneHotEncoder(drop='first'))]),
                                                  [1, 6])])),
                ('Scaling', StandardScaler()),
                ('model', LogisticRegression())])

In [74]:
pred=pipe.predict(x_test)

In [75]:
pred

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1])

In [76]:
y_test

     Survived
323         1
493         0
665         0
659         0
770         0
..        ...
639         0
753         0
410         0
505         0
729         0

[179 rows x 1 columns]

In [77]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, pred)

print (acc)

0.7597765363128491