In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/competitions/titanic/train.csv
/kaggle/input/competitions/titanic/test.csv
/kaggle/input/competitions/titanic/gender_submission.csv

## Use This DataSet for Praticing Column Transformer

In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/kaggle/input/competitions/titanic/train.csv')

In [17]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Other
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Other
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Other

In [18]:
df['Cabin'].nunique()

147

In [19]:
df['Cabin'].value_counts(
    
)

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E17            1
A24            1
C50            1
B42            1
C148           1
Name: count, Length: 147, dtype: int64

In [20]:
df["Deck"] = df["Cabin"].str[0]

In [21]:
df['Deck']=df['Deck'].fillna('Other')

In [22]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
Deck             0
dtype: int64

### Survived => Dependant Feature
### Sex => One Hot Encoding
### Age=> Simple Imputer
### Deck => Ordinal Encoding

In [50]:
from sklearn.model_selection import train_test_split
''
x_train,x_test,y_train,y_test = train_test_split(df.drop('Survived',axis=1),df['Survived'])

In [51]:
x_train[x_train['Deck']=='T']

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
339,340,1,"Blackwell, Mr. Stephen Weart",male,45.0,0,0,113784,35.5,T,S,T

In [52]:
x_train['Deck'].value_counts()

Deck
Other    521
C         39
B         35
D         24
E         22
A         12
F         10
G          4
T          1
Name: count, dtype: int64

In [53]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler,OrdinalEncoder

In [58]:
# Sex => One Hot Encoding
# Age=> Simple Imputer
# Deck => Ordinal Encoding
# fare => StandardScalar


num_cols_sc=['Fare']

cat_cols_oe =['Deck']

si= ['Age']

ohe = ['Sex']

transformer = ColumnTransformer(
    transformers=[
        ('fare1',StandardScaler(),num_cols_sc),
        ('deck2',OrdinalEncoder(),cat_cols_oe),
        ('Age3',SimpleImputer(strategy='mean'),si),
        ('Sex4',OneHotEncoder(drop='first'),ohe)
    ],remainder='passthrough'
)

x_train=transformer.fit_transform(x_train)
x_test=transformer.transform(x_test)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [60]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Other
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Other
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Other

In [62]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
from sklearn.impute import SimpleImputer

num_cols_sc = ['Fare']
cat_cols_oe = ['Deck']
si = ['Age']
ohe = ['Sex']

transformer = ColumnTransformer(
    transformers=[
        ('fare1', StandardScaler(), num_cols_sc),
        ('deck2', OrdinalEncoder(), cat_cols_oe),
        ('Age3', SimpleImputer(strategy='mean'), si),
        ('Sex4', OneHotEncoder(drop='first'), ohe)
    ],
    remainder='passthrough'
)

x_train = transformer.fit_transform(x_train)
x_test = transformer.transform(x_test)

ValueError: Specifying the columns using strings is only supported for dataframes.

In [65]:
x_train

array([[-0.037295428765701195, 7.0, 4.0, ..., '382652', nan, 'Q'],
       [-0.5318422856999997, 7.0, 17.0, ..., 'STON/O 2. 3101274', nan,
        'S'],
       [1.7003623912807204, 7.0, 30.0, ..., 'PC 17761', nan, 'C'],
       ...,
       [-0.1075435618529595, 7.0, 28.0, ..., '2003', nan, 'S'],
       [-0.5145151621852289, 7.0, 29.706554934823092, ..., '349201', nan,
        'S'],
       [-0.1075435618529595, 7.0, 64.0, ..., '693', nan, 'S']],
      dtype=object)

In [66]:
type(x_train)

numpy.ndarray

In [67]:
print(x_train[:5])

[[-0.037295428765701195 7.0 4.0 1.0 172 3 'Rice, Master. Arthur' 4 1
  '382652' nan 'Q']
 [-0.5318422856999997 7.0 17.0 1.0 434 3 'Kallio, Mr. Nikolai Erland' 0 0
  'STON/O 2. 3101274' nan 'S']
 [1.7003623912807204 7.0 30.0 0.0 538 1 'LeRoy, Miss. Bertha' 0 0
  'PC 17761' nan 'C']
 [-0.4784537045536834 7.0 29.706554934823092 1.0 869 3
  'van Melkebeke, Mr. Philemon' 0 0 '345777' nan 'S']
 [-0.06886100587966218 7.0 29.706554934823092 1.0 65 1
  'Stewart, Mr. Albert A' 0 0 'PC 17605' nan 'C']]

In [68]:
import pandas as pd

x_train_df = pd.DataFrame(x_train)

x_train_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11
0,-0.037295,7.0,4.0,1.0,172,3,"Rice, Master. Arthur",4,1,382652,NaN,Q
1,-0.531842,7.0,17.0,1.0,434,3,"Kallio, Mr. Nikolai Erland",0,0,STON/O 2. 3101274,NaN,S
2,1.700362,7.0,30.0,0.0,538,1,"LeRoy, Miss. Bertha",0,0,PC 17761,NaN,C
3,-0.478454,7.0,29.706555,1.0,869,3,"van Melkebeke, Mr. Philemon",0,0,345777,NaN,S
4,-0.068861,7.0,29.706555,1.0,65,1,"Stewart, Mr. Albert A",0,0,PC 17605,NaN,C

In [69]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Other
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Other
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Other

In [73]:
# Step 1: Import libraries
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder, OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score


# Step 2: Load dataset
# df = pd.read_csv("train.csv")


# Step 3: Feature extraction from Cabin
# Cabin = C123 → Deck = C
df["Deck"] = df["Cabin"].str[0].fillna("Other")


# Step 4: Select features and target
X = df[['Pclass','Sex','Age','Fare','Embarked','Deck']]
y = df['Survived']


# # Step 5: Train-test split
x_train, x_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# x_train, x_test, y_train, y_test = train_test_split(
#     df.drop(columns=['Survived']),
#     df['Survived'],
#     test_size=0.2,
#     random_state=42
# )


# Step 6: Create pipeline for Age
# Fill missing + scale
age_pipe = Pipeline([
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())
])


# Step 7: Column transformer
transformer = ColumnTransformer(
    transformers=[

        # Scale Fare
        ('fare', StandardScaler(), ['Fare']),

        # Age pipeline
        ('age', age_pipe, ['Age']),

        # One-hot encode categorical columns
        ('sex_embarked', OneHotEncoder(handle_unknown='ignore'),
         ['Sex', 'Embarked']),

        # Ordinal encode Deck
        ('deck', OrdinalEncoder(
            handle_unknown='use_encoded_value',
            unknown_value=-1
        ), ['Deck'])

    ],

    remainder='passthrough'
)


# Step 8: Transform data
x_train = transformer.fit_transform(x_train)
x_test = transformer.transform(x_test)


# Step 9: Build model
model = LogisticRegression()


# Step 10: Train model
model.fit(x_train, y_train)


# Step 11: Prediction
y_pred = model.predict(x_test)


# Step 12: Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8156424581005587