In [56]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

## Encoding Categorical Data | Ordinal Encoding | Label Encoder |

In [57]:
import pandas as pd
import numpy as np

In [75]:
df = pd.DataFrame({
    'Sex': ['Male', 'Female', 'Male', 'Female','Male', 'Female', 'Male', 'Female'],
    'Education': ['School', 'Graduate', 'Postgraduate', 'Graduate','School', 'Graduate', 'Postgraduate', 'Graduate'],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Pune','Pune', 'Mumbai', 'Delhi', 'Pune'],
    'Salary': [20000, 30000, 40000, 35000,20000, 30000, 40000, 35000]
})

In [76]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder

In [77]:
X=df[['Sex','Education','City']]
y=df['Salary']

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [78]:
x_train

      Sex     Education    City
6    Male  Postgraduate   Delhi
2    Male  Postgraduate   Delhi
5  Female      Graduate  Mumbai
0    Male        School    Pune
7  Female      Graduate    Pune
1  Female      Graduate  Mumbai

In [79]:
x_test

      Sex Education  City
3  Female  Graduate  Pune
4    Male    School  Pune

In [80]:
# Label Encoding

le=LabelEncoder()
x_train['Sex']=le.fit_transform(x_train['Sex'])
x_test['Sex']=le.transform(x_test['Sex'])

In [81]:
x_train

   Sex     Education    City
6    1  Postgraduate   Delhi
2    1  Postgraduate   Delhi
5    0      Graduate  Mumbai
0    1        School    Pune
7    0      Graduate    Pune
1    0      Graduate  Mumbai

In [82]:
x_test

   Sex Education  City
3    0  Graduate  Pune
4    1    School  Pune

In [83]:
# Orsinal Encoding
oe=OrdinalEncoder()


x_train[['Education']]=oe.fit_transform(x_train[['Education']])
x_test[['Education']]=oe.transform(x_test[['Education']])

In [84]:
x_train

   Sex  Education    City
6    1        1.0   Delhi
2    1        1.0   Delhi
5    0        0.0  Mumbai
0    1        2.0    Pune
7    0        0.0    Pune
1    0        0.0  Mumbai

In [85]:
x_test

   Sex  Education  City
3    0        0.0  Pune
4    1        2.0  Pune

In [86]:
y_train

6    40000
2    40000
5    30000
0    20000
7    35000
1    30000
Name: Salary, dtype: int64

In [87]:
y_test

3    35000
4    20000
Name: Salary, dtype: int64

In [88]:
df.columns

Index(['Sex', 'Education', 'City', 'Salary'], dtype='object')

In [89]:
city_encoded=pd.get_dummies(df['City'],prefix='City',dtype=int)

In [90]:
city_encoded

   City_Delhi  City_Mumbai  City_Pune
0           0            0          1
1           0            1          0
2           1            0          0
3           0            0          1
4           0            0          1
5           0            1          0
6           1            0          0
7           0            0          1