In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/vitthalbulbule/message/messages.csv
/kaggle/input/datasets/vitthalbulbule/message/orders.csv

In [4]:
import pandas as pd
import numpy as np

In [6]:
date = pd.read_csv('/kaggle/input/datasets/vitthalbulbule/message/orders.csv')
time=pd.read_csv('/kaggle/input/datasets/vitthalbulbule/message/messages.csv')

In [7]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [13]:
date['date']=pd.to_datetime(date['date'])

In [16]:
date['year']=date['date'].dt.year
date.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [19]:
date['month']= date['date'].dt.month
date.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [22]:
date['month_name']= date['date'].dt.month_name()
date.head()

        date  product_id  city_id  orders  year  month month_name
0 2019-12-10        5628       25       3  2019     12   December
1 2018-08-15        3646       14     157  2018      8     August
2 2018-10-23        1859       25       1  2018     10    October
3 2019-08-17        7292       25       1  2019      8     August
4 2019-01-06        4344       25       3  2019      1    January

In [25]:
date['day']= date['date'].dt.day
date.head()

        date  product_id  city_id  orders  year  month month_name  day
0 2019-12-10        5628       25       3  2019     12   December   10
1 2018-08-15        3646       14     157  2018      8     August   15
2 2018-10-23        1859       25       1  2018     10    October   23
3 2019-08-17        7292       25       1  2019      8     August   17
4 2019-01-06        4344       25       3  2019      1    January    6

In [29]:
date['day_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

In [33]:
date['is_weekend']=np.where(date['day_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,day_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,1

# Time

In [34]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [35]:
time['date']=pd.to_datetime(time['date'])

In [36]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [37]:
time['hour']=time['date'].dt.hour

In [39]:
time.head()

                 date                                                msg  hour
0 2013-12-15 00:50:00                           ищу на сегодня мужика 37     0
1 2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826    23
2 2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576     0
3 2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...     0
4 2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше    23

In [40]:
time['minute']=time['date'].dt.hour

In [41]:
time.head()

,date,msg,hour,minute
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,23
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,23

In [42]:
date['second']=date['date'].dt.second

In [44]:
time.head()

,date,msg,hour,minute
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,23
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,23