 Web Scrapping Using Python

In [1]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [2]:

headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage=requests.get("https://www.ambitionbox.com/list-of-companies?page=1",headers=headers).text

In [3]:
pip install lxml

Requirement already satisfied: lxml in c:\users\hp\appdata\local\programs\python\python313\lib\site-packages (6.0.2)Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:

soup=BeautifulSoup(webpage,'lxml')

In [5]:
company=soup.find_all('div', class_='companyCardWrapper__primaryInformation')

In [6]:
len(company)

20

In [7]:
name=[]
rating=[]
rating_count=[]
about=[]

for i in company:
    name.append(i.find("h2").text.strip())
    rating.append(i.find_all('div',class_='rating_text')[0].text.strip())
    rating_count.append(i.find('span',class_='companyCardWrapper__companyRatingCount').text.strip())
    about.append(i.find('span',class_="companyCardWrapper__interLinking").text.strip())



d={'name':name,'rating':rating,'rating_count':rating_count,'about':about}
df=pd.DataFrame(d)

In [8]:
name

['TCS',
 'Accenture',
 'Wipro',
 'Cognizant',
 'Capgemini',
 'HDFC Bank',
 'Infosys',
 'ICICI Bank',
 'HCLTech',
 'Tech Mahindra',
 'Genpact',
 'TP',
 'Jio',
 'Axis Bank',
 'Concentrix Corporation',
 'Amazon',
 'Reliance Retail',
 'iEnergizer',
 'LTIMindtree',
 'IBM']

In [9]:
len(rating)

20

In [10]:
rating

['3.3',
 '3.7',
 '3.6',
 '3.7',
 '3.7',
 '3.8',
 '3.5',
 '4.0',
 '3.4',
 '3.4',
 '3.6',
 '3.8',
 '4.4',
 '3.6',
 '3.6',
 '3.9',
 '3.9',
 '4.6',
 '3.6',
 '3.9']

In [11]:
len(rating_count)

20

In [12]:
rating_count

['(1.1L)',
 '(72.8k)',
 '(64.6k)',
 '(61k)',
 '(52.6k)',
 '(51.8k)',
 '(48.4k)',
 '(45.6k)',
 '(45.6k)',
 '(43.1k)',
 '(41.7k)',
 '(37.8k)',
 '(33.6k)',
 '(32.9k)',
 '(32k)',
 '(31.3k)',
 '(27.3k)',
 '(27.2k)',
 '(26.2k)',
 '(25.6k)']

In [13]:
len(about)

20

In [14]:
about

['IT Services & Consulting | Bengaluru +440 other locations',
 'IT Services & Consulting | Bengaluru +258 other locations',
 'IT Services & Consulting | Hyderabad +371 other locations',
 'IT Services & Consulting | Hyderabad +234 other locations',
 'IT Services & Consulting | Bengaluru +182 other locations',
 'Banking | Mumbai +1840 other locations',
 'IT Services & Consulting | Bengaluru +248 other locations',
 'Banking | Mumbai +1442 other locations',
 'IT Services & Consulting | Chennai +234 other locations',
 'IT Services & Consulting | Hyderabad +330 other locations',
 'Analytics & KPO | Hyderabad +182 other locations',
 'BPO | Mumbai +257 other locations',
 'Telecom | Mumbai +1961 other locations',
 'Banking | Mumbai +1515 other locations',
 'BPO | Bengaluru +179 other locations',
 'Internet | Bengaluru +524 other locations',
 'Retail | Mumbai +1157 other locations',
 'BPO | Noida +52 other locations',
 'IT Services & Consulting | Bengaluru +145 other locations',
 'IT Services & Consulting | Bengaluru +161 other locations']

In [15]:
df

,name,rating,rating_count,about
0,TCS,3.3,(1.1L),IT Services & Consulting | Bengaluru +440 othe...
1,Accenture,3.7,(72.8k),IT Services & Consulting | Bengaluru +258 othe...
2,Wipro,3.6,(64.6k),IT Services & Consulting | Hyderabad +371 othe...
3,Cognizant,3.7,(61k),IT Services & Consulting | Hyderabad +234 othe...
4,Capgemini,3.7,(52.6k),IT Services & Consulting | Bengaluru +182 othe...
5,HDFC Bank,3.8,(51.8k),Banking | Mumbai +1840 other locations
6,Infosys,3.5,(48.4k),IT Services & Consulting | Bengaluru +248 othe...
7,ICICI Bank,4.0,(45.6k),Banking | Mumbai +1442 other locations
8,HCLTech,3.4,(45.6k),IT Services & Consulting | Chennai +234 other ...
9,Tech Mahindra,3.4,(43.1k),IT Services & Consulting | Hyderabad +330 othe...
10,Genpact,3.6,(41.7k),Analytics & KPO | Hyderabad +182 other locations
11,TP,3.8,(37.8k),BPO | Mumbai +257 other locations
12,Jio,4.4,(33.6k),Telecom | Mumbai +1961 other locations
13,Axis Bank,3.6,(32.9k),Banking | Mumbai +1515 other locations
14,Concentrix Corporation,3.6,(32k),BPO | Bengaluru +179 other locations
15,Amazon,3.9,(31.3k),Internet | Bengaluru +524 other locations
16,Reliance Retail,3.9,(27.3k),Retail | Mumbai +1157 other locations
17,iEnergizer,4.6,(27.2k),BPO | Noida +52 other locations
18,LTIMindtree,3.6,(26.2k),IT Services & Consulting | Bengaluru +145 othe...
19,IBM,3.9,(25.6k),IT Services & Consulting | Bengaluru +161 othe...

In [16]:
final=pd.DataFrame()
for j in range (1,11):
    url="https://www.ambitionbox.com/list-of-companies?page={}".format(j)

    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage=requests.get(url,headers=headers).text


    
    soup=BeautifulSoup(webpage,'lxml')

    company=soup.find_all('div', class_='companyCardWrapper__primaryInformation')
    
    name=[]
    rating=[]
    rating_count=[]
    about=[]
    
    for i in company:
        name.append(i.find("h2").text.strip())
        rating.append(i.find_all('div',class_='rating_text')[0].text.strip())
        rating_count.append(i.find('span',class_='companyCardWrapper__companyRatingCount').text.strip())
        about.append(i.find('span',class_="companyCardWrapper__interLinking").text.strip())
    
    
    
    d={'name':name,'rating':rating,'rating_count':rating_count,'about':about}
    df=pd.DataFrame(d)

    final=pd.concat([final,df],ignore_index=True)

In [17]:
final

,name,rating,rating_count,about
0,TCS,3.3,(1.1L),IT Services & Consulting | Bengaluru +440 othe...
1,Accenture,3.7,(72.8k),IT Services & Consulting | Bengaluru +258 othe...
2,Wipro,3.6,(64.6k),IT Services & Consulting | Hyderabad +371 othe...
3,Cognizant,3.7,(60.9k),IT Services & Consulting | Hyderabad +234 othe...
4,Capgemini,3.7,(52.6k),IT Services & Consulting | Bengaluru +182 othe...
...,...,...,...,...
195,Pidilite Industries,4.2,(3.9k),Chemicals | Mumbai +320 other locations
196,Oyo Rooms,3.0,(3.9k),Internet | Gurugram +121 other locations
197,Aditya Birla Sun Life Insurance,4.0,(3.8k),Insurance | Mumbai +499 other locations
198,American Express,4.1,(3.8k),Financial Services | Gurugram +55 other locations
199,Grasim Industries,4.0,(3.8k),Building Material | Bharuch +251 other locations

In [18]:
final.shape

(200, 4)

In [20]:
final.to_csv("Amdox_Dataset.csv",index=False)